import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import LoginButton from "../components/login-button";
import LogoutButton from "../components/logout-button";
import { useSession } from "next-auth/react";

export default function Home() {
  const handleSubmit = async (e) => {
    e.preventDefault();
    console.log("handling submit");
    let signedUrl = null;
    await fetch("/api/get_signed_url", { method: "GET" })
      .then((res) => res.json())
      .then((json) => {
        console.log(json);
        signedUrl = json.signedUrl;
      })
      .catch((err) => console.error(err));

    const input = document.getElementById("file-upload-input");
    console.log("uploading file");
    // const fd = new FormData();
    // fd.append("uploadedFile", input.files[0]);
    // console.log("appended file");

    const response = await fetch(signedUrl, {
      method: "PUT",
      body: input.files[0],
    });
    // fetch("/api/file_upload", { method: "POST", body: { text: "hello" } });
    console.log(
      `\nResponse returned by signed URL: ${await response.text()}\n`
    );
    console.log("done with submission");
  };

  const { data: session } = useSession();
  if (!session) {
    return <LoginButton />;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <LogoutButton />

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <form className={styles.form} onSubmit={handleSubmit}>
          <input type="file" id="file-upload-input"></input>
          <input type="submit"></input>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
